### PR TITLE
Switch to Tauri

### PR DESCRIPTION
**Pull request by dignifiedquire**
based on #10

### CODE REVIEW

**Comment by Septias** [comment]
We might want to add a hint to the readme on how to get `cargo tauri dev` command working. I looked around the website but only found the normal js cli which works like `tauri dev` but no info on how to add the cargo plugin.

**Comment by dignifiedquire** [comment]
`cargo intall tauri-cli`

**Comment by Septias** [comment]
could not find `tauri-cli` in registry `https://github.com/rust-lang/crates.io-index` with version `*`

**Comment by dignifiedquire** [comment]
add a —version flag, with the latest on crates.io. it is a prerelease, which is why regular install doesn’t yet pick it up

**Pull request merged**
