### PR TITLE
Account Import

### PR DESCRIPTION
**Pull request by Septias**

### CODE REVIEW

**Comment by Septias** [comment]
@dignifiedquire, you tried to bring our dc-core dep (which is >4000 commits behind) to the newest version of dc-core but didn't finish it. For the Backend integration, I need to make an API change in core and would like to do so at the master's head. Are you planning on doing that upgrade again, or should I try to do it myself?

**Comment by Septias** [comment]
It would also be nice to have a consistent stream of the backup file from the frontend -> backend instead of the current implementation where the whole file is loaded on the frontend via [gloo_file::callbacks::read_as_bytes](https://docs.rs/gloo-file/0.1.0/gloo_file/callbacks/fn.read_as_bytes.html) and then send to the backend. (this is heavily inspired by [this](https://github.com/yewstack/yew/tree/master/examples/file_upload) example)
With a consistent stream, the load-time can be halved which can make quite a difference with huge backup files.
But since we got more pressing issues I would personally delay that rework to a future pr.

**Comment by dignifiedquire** [comment]
> Are you planning on doing that upgrade again, or should I try to do it myself?

I started on it, it is a bit more involved, but hopefully will have sth working soon

**Comment by dignifiedquire** [comment]
> But since we got more pressing issues I would personally delay that rework to a future pr.

Yes, lets get sth working for now, and do that optimization later

**Comment by dignifiedquire** [comment]
https://github.com/dignifiedquire/dc40/pull/16 does the trick

**Comment by Septias** [comment]
Very nice, I might finish this pr the next few days but I'm also going on vacation so this could take a while

**Comment by Septias** [comment]
closing this in favor of #17 which does the same thing but with a different approach

**Pull request closed without merging**
