### PR TITLE
Account import

### PR DESCRIPTION
**Pull request by Septias**
Add feature to import an account-backup to use dc40 as a second device

### CODE REVIEW

**Comment by dignifiedquire** [comment]
can you rebase on `master`, I merged the tauri branch

**Comment by Septias** [comment]
yeah just saw that

**Comment by Septias** [comment]
wait a sec why did they become 33 commits ? O.o
How do I clean this?

**Comment by dignifiedquire** [comment]
hmm, what exactly did you do? 
easiest solution might be make a new branch from `master` and then cherry-pick the commits you want to merge over

**Comment by Septias** [comment]
I just executed `git rebase master` in my local repo and pushed it.

**Comment by Septias** [comment]
Idk there was some stupid shit going on so I wasn't able to cherry pick without merge conflict. I ended up copying manually into my new branch

**Pull request closed without merging**
