### PR TITLE
Create chat panel

### PR DESCRIPTION
**Pull request by Septias**
Todo 

- [x] Panel
- [x] Search-function
- [x] Group-name
- [x] Backend chat-creation
- [x] Fix window-manager 
- [x] Chat autoselect after creation

### CODE REVIEW

**Comment by dignifiedquire** [comment]
I see some conflicts with master :(

**Comment by Septias** [comment]
:(

**Review by Simon-Laux — CHANGES_REQUESTED** [review]
rebase needed, there are some commits in this pr that don't belong into it.

**Comment by Septias** [comment]
Yeah, I've got no time to work on this atm :/. When I wrote it I was sure I would have got it done before anyone else did any changes because I was the only one active at that time

**Comment by Septias** [comment]
> rebase needed, there are some commits in this pr that don't belong into it.

Atm I'm the only one working here. Since the pr is ready to merge we can just do that I guess

**Comment by dignifiedquire** [comment]
@Septias feel free to merge if it works :)

**Pull request merged**
