### PR TITLE
feat: update to latest core and new accounts structure

### PR DESCRIPTION
**Pull request by dignifiedquire**
- new core
- use accounts structure
- login works

### CODE REVIEW

**Comment by Septias** [comment]
dc-core-rust doesn't have a branch "fix-messages-read" which you add in cargo.toml
At least I can't find it and Rust analyzer fails on this problem.

**Comment by dignifiedquire** [comment]
fixed

**Comment by Septias** [comment]
did you push it?

**Comment by dignifiedquire** [comment]
yes, see above

**Comment by Septias** [comment]
oof idk how i missed that tbh

**Pull request merged**
